using Router.Contracts.Plugins;

namespace Plugins.UniversalForward;


public sealed partial class UniversalForwardTerminal
{
    /// <summary>渠道、模型、Key 和连接测试管理页面。</summary>
    private static PluginMainPage CreateMainPage() => new(
        "UniversalForward 渠道管理",
        """
        <!doctype html>
        <html lang="zh-CN">
        <head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
        <style>
        :root{font:15px system-ui,sans-serif;color:#172b35;background:#f5f7fa}*{box-sizing:border-box}body{margin:0;padding:24px}main{max-width:1100px;margin:auto}h1{font-size:26px;margin:0}header,.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}header{justify-content:space-between;margin-bottom:20px}button,input,textarea,select{font:inherit}button{cursor:pointer;border:1px solid #cbd5df;background:white;border-radius:8px;padding:9px 14px}button.primary{background:#087f8c;color:white;border-color:#087f8c}button:disabled{opacity:.55;cursor:wait}input,textarea,select{width:100%;padding:10px;border:1px solid #cbd5df;border-radius:8px}input[type=checkbox]{width:auto}textarea{min-height:100px;resize:vertical}label{display:block;margin-bottom:5px}#keyRows .card{margin:10px 0}#keyRows input{margin:4px 0}#testKey{margin-bottom:12px}small,.muted{color:#526572}#notice{background:#fff2cf;padding:12px;border-radius:8px;line-height:1.7;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:16px;margin-top:16px}.card{background:white;border:1px solid #dce3e9;border-radius:12px;padding:18px;overflow-wrap:anywhere}.card h2{font-size:18px;margin:0 0 8px}.card p{line-height:1.6}.empty{padding:24px}.error{color:#b42318;white-space:pre-wrap}dialog{width:min(760px,95vw);max-height:90vh;border:1px solid #cbd5df;border-radius:14px;padding:22px}dialog::backdrop{background:#172b3580}.fields{display:grid;grid-template-columns:1fr 1fr;gap:15px}.full{grid-column:1/-1}.checks{display:flex;gap:12px;flex-wrap:wrap}.candidates{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.selected{background:#d7f3ed;border-color:#087f8c}.footer{margin-top:20px;justify-content:flex-end}pre{white-space:pre-wrap}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #6fc9ce;outline-offset:2px}@media(max-width:600px){body{padding:12px}.fields{grid-template-columns:1fr}}
        </style></head>
        <body><main>
        <header><div><h1>UniversalForward 渠道管理</h1><p class="muted">通用上游 · 手填或选择模型</p></div><div class="actions"><button id="reload">刷新</button><button id="add" class="primary">添加渠道</button></div></header>
        <div id="notice">支持手填或选择模型，以及渠道重试配置。重试可能产生费用。</div>
        <div id="message" role="status" aria-live="polite"></div>
        <label for="filter">筛选渠道或模型</label><input id="filter" placeholder="名称、地址、模型">
        <section id="cards" class="grid" aria-live="polite"></section>
        </main>
        <dialog id="editor"><form id="accountForm">
        <header><h2 id="formTitle">添加渠道</h2><button type="button" id="close" aria-label="关闭">×</button></header>
        <input name="id" type="hidden">
        <div class="fields">
        <div><label for="label">渠道名称</label><input id="label" name="label" required></div>
        <div><label for="weight">权重（0–1000）</label><input id="weight" name="weight" type="number" min="0" max="1000" required value="100"></div>
        <div class="full"><label for="baseUrl">Base URL</label><input id="baseUrl" name="baseUrl" required placeholder="https://api.example.com/v1"></div>
        <div class="full"><label for="keySelectionMode">Key 分配策略</label><select id="keySelectionMode"><option value="roundRobin">轮询</option><option value="random">随机</option><option value="priority">主备顺序</option></select><p class="muted">每次请求及其重试使用同一个 Key。主备顺序使用第一个启用 Key。</p><div id="keyRows"></div><label for="keyBatch">批量添加 Key（每行一个，最多100个）</label><textarea id="keyBatch" autocomplete="off" spellcheck="false"></textarea><button id="keyAdd" type="button">添加到列表</button><small>Key 以掩码展示，留空保留原密钥。启用后参与分配。</small></div>
        <div class="full"><label>允许端点</label><div id="endpoints" class="checks"></div></div>
        <div class="full"><label for="models">允许模型（每行一个，可直接输入）</label><textarea id="models" name="models" required spellcheck="false"></textarea><small>手动填写模型，或从候选列表中选择。</small><label for="discoveryKey">发现 / 刷新使用的 Key（已保存配置）</label><select id="discoveryKey"></select><div class="actions"><button id="refreshModels" type="button">刷新已保存候选</button><button id="discover" type="button">获取候选模型（可选）</button></div><div id="candidates" class="candidates"></div></div>
        <div class="full"><label>每模型上游协议</label><small>配置模型的上游接口与认证方式，内容按上游格式透传。</small><button id="syncProtocols" type="button">同步当前模型</button><div id="modelProtocols"></div></div>
        <div class="full"><label><input name="enabled" type="checkbox" checked> 启用渠道</label></div>
        <div><label for="maxRetries">重试次数（0–10）</label><input id="maxRetries" name="maxRetries" type="number" min="0" max="10" value="0" required></div>
        <div><label for="headerTimeoutSeconds">响应头超时（秒）</label><input id="headerTimeoutSeconds" name="headerTimeoutSeconds" type="number" min="1" max="3600" value="60" required></div>
        <div><label for="totalTimeoutSeconds">总时限（秒）</label><input id="totalTimeoutSeconds" name="totalTimeoutSeconds" type="number" min="1" max="3600" value="180" required></div>
        <div><label for="streamIdleTimeoutSeconds">流空闲超时（秒）</label><input id="streamIdleTimeoutSeconds" name="streamIdleTimeoutSeconds" type="number" min="1" max="3600" value="60" required></div>
        <div class="full"><label for="retryStatusCodes">自动重试状态码</label><input id="retryStatusCodes" name="retryStatusCodes" value="100-199,300-399,401-407,409-499,500-503,505-523,525-599"><small>填写触发重试的上游状态码。</small></div>
        <div class="full"><label for="statusCodeMapping">状态码映射（JSON）</label><textarea id="statusCodeMapping" name="statusCodeMapping">{}</textarea><small>示例 {"400":500,"429":503}。最终返回时映射，不改变重试判定和正文。</small><button id="mappingTemplate" type="button">填入模板</button></div>
        <div class="full"><label for="headerOverride">请求头覆盖（JSON）</label><textarea id="headerOverride" name="headerOverride" spellcheck="false">{}</textarea><small>支持 {api_key}、{client_header:NAME}、*、re: 和 regex:；显式覆盖优先。固定认证值可能使多 Key 分配无效；动态认证请使用 {api_key}。</small><div class="actions"><button type="button" id="headerTemplate">填入模板</button><button type="button" id="headerPass">透传模板</button><button type="button" id="headerClear">清空</button><button type="button" id="headerFormat">格式化 JSON</button><button type="button" id="headerCopy">复制</button></div></div>
        <div class="full" hidden><label for="extraParams">高级参数 / 请求头覆盖（JSON）</label><textarea id="extraParams" name="extraParams" spellcheck="false">{}</textarea><small>使用 ReplaceHeaders 对象覆盖请求头。API Key 保存在账号凭据中，不返回到页面。</small><div class="actions"><button id="template" type="button">填入覆盖模板</button><button id="format" type="button">格式化 JSON</button></div></div>
        </div><p id="formError" class="error" role="alert"></p><div class="actions footer"><button id="cancel" type="button">取消</button><button id="save" class="primary" type="submit">保存渠道</button></div>
        </form></dialog>
        <dialog id="testDialog" aria-labelledby="testTitle">
        <header><h2 id="testTitle">测试渠道连接</h2><button id="testClose" type="button" aria-label="关闭测试">×</button></header>
        <p class="muted">按已保存配置串行测试模型连接，可能产生费用。</p>
        <div class="fields"><div><label for="testEndpoint">端点类型</label><select id="testEndpoint" style="width:100%;padding:10px"></select></div><div><label><input id="testStream" type="checkbox"> 流式模式</label></div></div>
        <label for="testKey">测试使用的 Key</label><select id="testKey"></select><label for="testFilter">筛选模型</label><input id="testFilter" placeholder="输入模型名称">
        <div class="actions" style="margin:12px 0"><button id="testAll" class="primary">测试全部</button><button id="testSelected">测试勾选</button><button id="testCancel" disabled>取消测试</button><button id="testResume" hidden>重试查询</button></div>
        <p id="testProgress" role="status" aria-live="polite"></p><p id="testError" class="error" role="alert"></p>
        <div style="overflow:auto;max-height:48vh"><table style="width:100%;min-width:640px;text-align:left;border-collapse:collapse"><thead><tr><th><input id="testSelectAll" type="checkbox" aria-label="勾选可见模型"></th><th>模型</th><th>状态</th><th>结果</th><th>操作</th></tr></thead><tbody id="testRows"></tbody></table></div>
        <details><summary>结果详情</summary><pre id="testDetails"></pre></details></dialog>
        <script>
        (()=>{'use strict';
        const $=id=>document.getElementById(id),form=$('accountForm'),dialog=$('editor');
        const api=(method,path,body)=>window.Router2API.request(method,path,body);
        const paths=['/v1/chat/completions','/v1/responses','/v1/messages','/v1/completions'];
        let accounts=[],candidates=[],modelProtocolDraft={},keyDraft=[],deletedKeyIds=[],keyRevision=0;
        const keyModes={roundRobin:"轮询",random:"随机",priority:"主备顺序"};
        const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
        const message=(text,error=false)=>{$('message').textContent=text;$('message').className=error?'error':'muted'};
        const modelIds=()=>[...new Set(form.elements.models.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];
        function json(){const value=JSON.parse(form.elements.extraParams.value||'{}');if(!value||Array.isArray(value)||typeof value!=='object')throw Error('高级参数必须是 JSON 对象');return value}
        function showCandidates(){const root=$('candidates');root.replaceChildren();const selected=new Set(modelIds());for(const model of candidates){const b=el('button',model,selected.has(model)?'selected':'');b.type='button';b.addEventListener('click',()=>{const ids=modelIds();form.elements.models.value=(selected.has(model)?ids.filter(x=>x!==model):[...ids,model]).join('\n');showCandidates()});root.append(b)}}
        function open(account){modelProtocolDraft=structuredClone(account?.modelProtocols||{});form.reset();$('formError').textContent='';$('formTitle').textContent=account?'编辑渠道':'添加渠道';for(const key of ['id','label','baseUrl'])form.elements[key].value=account?.[key]||'';form.elements.weight.value=account?.weight??100;form.elements.enabled.checked=account?.enabled??true;form.elements.models.value=(account?.models||[]).join('\n');form.elements.extraParams.value=account?.extraParams||'{}';keyDraft=(account?.keys||[]).map(k=>({...k,secret:''}));deletedKeyIds=[];keyRevision=account?.keyRevision??0;$('keySelectionMode').value=account?.keySelectionMode||'roundRobin';renderKeys();fillKeyOptions($('discoveryKey'),account?.keys||[],false);$('refreshModels').disabled=!account;form.elements.headerOverride.value=JSON.stringify(account?.headerOverride||{},null,2);const policy=account?.requestPolicy||{};for(const [key,fallback] of Object.entries({maxRetries:0,headerTimeoutSeconds:60,totalTimeoutSeconds:180,streamIdleTimeoutSeconds:60,retryStatusCodes:'100-199,300-399,401-407,409-499,500-503,505-523,525-599'}))form.elements[key].value=policy[key]??fallback;form.elements.statusCodeMapping.value=JSON.stringify(policy.statusCodeMapping||{},null,2);const selected=new Set(account?.endpoints||paths);$('endpoints').replaceChildren();for(const path of paths){const label=el('label'),box=el('input');box.type='checkbox';box.name='endpoints';box.value=path;box.checked=selected.has(path);label.append(box,document.createTextNode(' '+path));$('endpoints').append(label)}candidates=account?.availableModels||[];showCandidates();renderProtocols();dialog.showModal()}
        async function action(button,work){button.disabled=true;try{await work()}catch(e){message(e.message||String(e),true)}finally{button.disabled=false}}
        function render(){const root=$('cards');root.replaceChildren();const q=$('filter').value.toLowerCase();const visible=accounts.filter(a=>[a.label,a.baseUrl,...(a.models||[])].join(' ').toLowerCase().includes(q));if(!visible.length){root.append(el('p','暂无匹配渠道','empty'));return}for(const a of visible){const card=el('article',undefined,'card');card.append(el('h2',a.label),el('p',a.baseUrl,'muted'),el('p',`${a.enabled?'启用':'停用'} · 权重 ${a.weight} · ${a.models?.length||0} 个模型 · Key ${a.enabledKeyCount??0}/${a.totalKeyCount??0} · ${keyModes[a.keySelectionMode]||"轮询"}`),el('p',(a.models||[]).join('、')));const actions=el('div',undefined,'actions');for(const [title,work] of [['编辑',async()=>open(a)],['测试连接',async()=>openTests(a)],['刷新候选',async()=>{open(a);$('discoveryKey').focus()}],['删除',async()=>{if(!confirm(`删除渠道“${a.label}”？`))return;await api('POST','accounts/delete',{id:a.id});await load()}]]){const button=el('button',title);button.addEventListener('click',()=>action(button,work));actions.append(button)}card.append(actions);root.append(card)}}
        async function load(){try{const data=await api('GET','accounts');accounts=data.accounts||[];render()}catch(e){message(e.message||String(e),true)}}
        $('add').addEventListener('click',()=>open(null));$('reload').addEventListener('click',()=>action($('reload'),load));$('filter').addEventListener('input',render);$('models').addEventListener('input',showCandidates);for(const id of ['close','cancel'])$(id).addEventListener('click',()=>dialog.close());
        $('format').addEventListener('click',()=>{try{form.elements.extraParams.value=JSON.stringify(json(),null,2);$('formError').textContent=''}catch(e){$('formError').textContent=e.message}});
        $('template').addEventListener('click',()=>{try{const value=json();value.ReplaceHeaders??={'User-Agent':'UniversalForward'};form.elements.extraParams.value=JSON.stringify(value,null,2)}catch(e){$('formError').textContent=e.message}});
        async function discover(refresh){const id=form.elements.id.value;if(!id)throw Error('请先保存渠道和 Key，再获取候选');const data=await api('POST',refresh?'models/refresh':'models/discover',{id,keyId:$('discoveryKey').value||null});candidates=data.models||[];showCandidates();}
        for(const [id,refresh] of [['discover',false],['refreshModels',true]])$(id).addEventListener('click',async()=>{const button=$(id);button.disabled=true;$('formError').textContent='';try{await discover(refresh)}catch(e){$('formError').textContent=e.message}finally{button.disabled=false}});
        form.addEventListener('submit',async event=>{event.preventDefault();const button=$('save');button.disabled=true;$('formError').textContent='';try{const endpoints=[...form.querySelectorAll('input[name=endpoints]:checked')].map(x=>x.value);if(!endpoints.length)throw Error('至少选择一个端点');const models=modelIds();if(!models.length)throw Error('请手填或选择至少一个模型');const saved=await api('POST','accounts/save',{id:form.elements.id.value||null,label:form.elements.label.value,baseUrl:form.elements.baseUrl.value,keys:readKeys(),deletedKeyIds,keyRevision,keySelectionMode:$('keySelectionMode').value,weight:Number(form.elements.weight.value),enabled:form.elements.enabled.checked,endpoints,models,modelProtocols:readProtocols(),requestPolicy:readPolicy(),headerOverride:readHeaderOverride(),extraParams:json()});dialog.close();await load();message(saved.warning||'渠道已保存',!!saved.warning)}catch(e){$('formError').textContent=e.message}finally{button.disabled=false}});
        function fillKeyOptions(select,keys,testing){select.replaceChildren();for(const [value,title] of testing?[['strategy','按渠道策略'],['all','全部启用 Key']]:[['','第一个启用 Key']]){const opt=el('option',title);opt.value=value;select.append(opt)}for(const key of keys.filter(k=>k.enabled)){const opt=el('option',(key.name||key.id)+' · '+key.masked);opt.value=testing?'key:'+key.id:key.id;select.append(opt)}}
        function renderKeys(){const root=$('keyRows');root.replaceChildren();keyDraft.forEach((key,index)=>{const row=el('div',undefined,'card');row.append(el('strong',`#${index+1} · ${key.masked||'新 Key'}`));const name=el('input');name.value=key.name;name.placeholder='Key 名称';name.setAttribute('aria-label',`Key ${index+1} 名称`);name.addEventListener('input',()=>key.name=name.value);const secret=el('input');secret.type='password';secret.autocomplete='new-password';secret.value=key.secret;secret.placeholder=key.id?'留空保持现有密钥':'输入新密钥';secret.setAttribute('aria-label',`Key ${index+1} 密钥`);secret.addEventListener('input',()=>key.secret=secret.value);const enabled=el('input');enabled.type='checkbox';enabled.checked=key.enabled;enabled.addEventListener('change',()=>key.enabled=enabled.checked);const label=el('label');label.append(enabled,document.createTextNode(' 启用 Key'));row.append(name,secret,label);const actions=el('div',undefined,'actions');for(const [title,delta] of [['上移',-1],['下移',1]]){const button=el('button',title);button.type='button';button.disabled=index+delta<0||index+delta>=keyDraft.length;button.addEventListener('click',()=>{[keyDraft[index],keyDraft[index+delta]]=[keyDraft[index+delta],keyDraft[index]];renderKeys()});actions.append(button)}const remove=el('button','删除 Key');remove.type='button';remove.addEventListener('click',()=>{if(!confirm('确认删除此 Key？保存后生效。'))return;if(key.id)deletedKeyIds.push(key.id);keyDraft.splice(index,1);renderKeys()});actions.append(remove);row.append(actions);root.append(row)})}
        $('keyAdd').addEventListener('click',()=>{const lines=$('keyBatch').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(keyDraft.length+lines.length>100){$('formError').textContent='每渠道最多100个 Key';return}const existing=new Set(keyDraft.map(k=>k.secret).filter(Boolean));for(const secret of lines){if(existing.has(secret)){$('formError').textContent='批量内容含重复 Key';return}existing.add(secret)}for(const secret of lines)keyDraft.push({id:'',name:'Key '+(keyDraft.length+1),secret,enabled:true});$('keyBatch').value='';$('formError').textContent='';renderKeys()});
        function readKeys(){if($('keyBatch').value.trim())throw Error('请先将批量 Key 添加到列表');return keyDraft.map(({id,name,secret,enabled})=>({id,name,secret:secret.trim(),enabled}))}
        function readPolicy(){const map=JSON.parse(form.elements.statusCodeMapping.value||'{}');if(!map||Array.isArray(map)||typeof map!=='object')throw Error('状态码映射必须为 JSON 对象');return {maxRetries:Number(form.elements.maxRetries.value),headerTimeoutSeconds:Number(form.elements.headerTimeoutSeconds.value),totalTimeoutSeconds:Number(form.elements.totalTimeoutSeconds.value),streamIdleTimeoutSeconds:Number(form.elements.streamIdleTimeoutSeconds.value),retryStatusCodes:form.elements.retryStatusCodes.value,statusCodeMapping:map}}
        $('mappingTemplate').addEventListener('click',()=>{form.elements.statusCodeMapping.value=JSON.stringify({'400':500,'429':503},null,2)});
        const testState={account:null,selected:new Set(),rows:new Map(),targets:new Set(),jobId:null,active:false,starting:false,cancelling:false,running:null,timer:null,epoch:0};
        const testBusy=()=>testState.active||testState.starting;
        function updateTestControls(){const busy=testBusy();for(const id of ['testAll','testSelected','testEndpoint','testStream','testKey'])$(id).disabled=busy;$('testCancel').disabled=!testState.active||testState.cancelling;$('testSelectAll').disabled=busy;}
        const resultId=(model,keyId)=>JSON.stringify([model,keyId??null]);
        function renderTests(){const root=$('testRows');root.replaceChildren();const q=$('testFilter').value.toLowerCase();for(const model of testState.account?.models||[]){if(!model.toLowerCase().includes(q))continue;const row=el('tr'),check=el('td'),select=el('input');select.type='checkbox';select.checked=testState.selected.has(model);select.disabled=testBusy();select.setAttribute('aria-label','选择 '+model);select.addEventListener('change',()=>{if(select.checked)testState.selected.add(model);else testState.selected.delete(model)});check.append(select);const results=[...testState.rows.values()].filter(r=>r.model===model);const pending=testState.active&&testState.targets.has(model)&&results.length<(testState.combinations||[]).filter(c=>c.model===model).length;const state=pending?testState.running===model?'测试中':'排队中':results.length?results.every(r=>r.cancelled)?'已取消':results.every(r=>r.success)?'成功':'失败':'未测试';const summary=el('td');for(const result of results){const line=el('div',`${result.keyName||result.keyId||'按策略'} · ${result.cancelled?'已取消':result.success?'成功':'失败'} · ${result.originalStatus??'-'} → ${result.mappedStatus??'-'} · ${result.durationMs??'-'}ms · 重试 ${result.retries??0}次${result.firstEventMs!=null?' · 首事件 '+result.firstEventMs+'ms':''}`);summary.append(line)}row.append(check,el('td',model),el('td',state),summary);const ops=el('td'),run=el('button','测试');run.disabled=testBusy();run.addEventListener('click',()=>startTests([model]));ops.append(run);if(results.length){const detail=el('button','详情');detail.addEventListener('click',()=>{$('testDetails').textContent=JSON.stringify(results,null,2);$('testDetails').parentElement.open=true});ops.append(detail)}row.append(ops);root.append(row)}updateTestControls()}
        function openTests(account){$('testTitle').textContent='测试渠道连接：'+account.label;if(testBusy()&&testState.account?.id!==account.id){message('请先取消或等待当前渠道测试完成',true);return}if(!testBusy())fillKeyOptions($('testKey'),account.keys||[],true);if(!testBusy()||testState.account?.id!==account.id){clearTimeout(testState.timer);testState.epoch++;Object.assign(testState,{account,selected:new Set(),rows:new Map(),targets:new Set(),jobId:null,active:false,running:null});$('testProgress').textContent='';$('testDetails').textContent='';$('testFilter').value='';$('testError').textContent='';$('testEndpoint').replaceChildren();const auto=el('option','自动选择');auto.value='';$('testEndpoint').append(auto);for(const endpoint of account.endpoints||[]){const option=el('option',endpoint);option.value=endpoint;$('testEndpoint').append(option)}$('testStream').checked=false}renderTests();if(!$('testDialog').open)$('testDialog').showModal();}
        async function startTests(models){if(testBusy())return;const choice=$('testKey').value;const keyMode=choice.startsWith('key:')?'specified':choice;const keyId=keyMode==='specified'?choice.slice(4):null;const keys=keyMode==='all'?(testState.account.keys||[]).filter(k=>k.enabled).map(k=>k.id):[keyId];const total=models.length*keys.length;if(!total||total>100){$('testError').textContent='请选择1–100个模型 × Key 组合';return}if(!confirm(`将发送 ${total} 个模型 × Key 测试请求，可能产生费用。继续？`))return;testState.starting=true;testState.targets=new Set(models);testState.combinations=models.flatMap(model=>keys.map(keyId=>({model,keyId})));for(const [id,row] of testState.rows)if(models.includes(row.model))testState.rows.delete(id);$('testError').textContent='';$('testResume').hidden=true;renderTests();try{const job=await api('POST','tests/start',{accountId:testState.account.id,models,keyMode,keyId,endpoint:$('testEndpoint').value||null,stream:$('testStream').checked});testState.jobId=job.id;testState.active=true;testState.epoch++;$('testProgress').textContent='测试已提交';await pollTests(testState.epoch)}catch(e){$('testError').textContent=e.message||String(e)}finally{testState.starting=false;renderTests()}}
        async function pollTests(epoch){if(epoch!==testState.epoch||!testState.active)return;clearTimeout(testState.timer);try{const job=await api('GET','tests/status?id='+encodeURIComponent(testState.jobId));if(epoch!==testState.epoch)return;const state=typeof job.state==='number'?['Queued','Running','Completed','Failed','Cancelled'][job.state]:job.state;const progress=job.progress||{};const rows=job.result?.rows||progress.rows||[];for(const row of rows)testState.rows.set(resultId(row.model,row.keyId),row);testState.running=progress.running||null;$('testProgress').textContent=`${({Queued:'排队中',Running:'测试中',Completed:'已完成',Failed:'失败',Cancelled:'已取消'})[state]||state} · ${progress.completed??rows.length}/${progress.total??testState.combinations?.length??0}`;$('testResume').hidden=true;if(['Completed','Failed','Cancelled'].includes(state)){testState.active=false;testState.cancelling=false;testState.running=null;for(const combo of testState.combinations||[]){const exists=combo.keyId===null?[...testState.rows.values()].some(r=>r.model===combo.model):testState.rows.has(resultId(combo.model,combo.keyId));if(!exists)testState.rows.set(resultId(combo.model,combo.keyId),{...combo,success:false,cancelled:state==='Cancelled',error:job.error||'测试未完成'})}if(job.error)$('testError').textContent=job.error}else if(['Queued','Running'].includes(state)){testState.timer=setTimeout(()=>pollTests(epoch),800)}else{throw Error('无法识别任务状态，请重新查询')}renderTests()}catch(e){if(epoch!==testState.epoch)return;$('testError').textContent='查询失败：'+(e.message||String(e));$('testResume').hidden=false;updateTestControls()}}
        $('testAll').addEventListener('click',()=>startTests(testState.account.models||[]));$('testSelected').addEventListener('click',()=>startTests([...testState.selected]));$('testFilter').addEventListener('input',renderTests);$('testSelectAll').addEventListener('change',()=>{const q=$('testFilter').value.toLowerCase();for(const model of testState.account.models||[])if(model.toLowerCase().includes(q)){if($('testSelectAll').checked)testState.selected.add(model);else testState.selected.delete(model)}renderTests()});$('testResume').addEventListener('click',()=>pollTests(testState.epoch));$('testClose').addEventListener('click',()=>$('testDialog').close());
        $('testCancel').addEventListener('click',async()=>{testState.cancelling=true;updateTestControls();try{await api('POST','tests/cancel',{id:testState.jobId});$('testProgress').textContent='已申请取消，正在等待任务退出';await pollTests(testState.epoch)}catch(e){testState.cancelling=false;$('testError').textContent=e.message||String(e);updateTestControls()}});
        function readHeaderOverride(){const value=JSON.parse(form.elements.headerOverride.value||'{}');if(!value||Array.isArray(value)||typeof value!=='object')throw Error('请求头覆盖必须是 JSON 对象');return value}
        $('headerTemplate').addEventListener('click',()=>{form.elements.headerOverride.value=JSON.stringify({'*':true,'re:^X-Trace-.*$':true,'X-Foo':'{client_header:X-Foo}',Authorization:'Bearer {api_key}'},null,2)});
        $('headerPass').addEventListener('click',()=>{if(confirm('将透传所有可允许的客户端请求头，认证及连接控制头除外。继续？'))form.elements.headerOverride.value=JSON.stringify({'*':true},null,2)});
        $('headerClear').addEventListener('click',()=>{form.elements.headerOverride.value=''});
        $('headerFormat').addEventListener('click',()=>{try{form.elements.headerOverride.value=JSON.stringify(readHeaderOverride(),null,2)}catch(e){$('formError').textContent=e.message}});
        $('headerCopy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(form.elements.headerOverride.value)}catch(e){$('formError').textContent='无法写入剪贴板，请手动复制'}});
        const protocolLabels={chat:'Chat Completions',responses:'Responses',messages:'Claude Messages',completions:'Completions'};
        function renderProtocols(){const root=$('modelProtocols');root.replaceChildren();for(const model of modelIds()){const configured=modelProtocolDraft[model];const row=el('div',undefined,'card');row.append(el('strong',model));const enabled=el('input');enabled.type='checkbox';enabled.checked=!!configured;const enableLabel=el('label');enableLabel.append(enabled,document.createTextNode(' 指定支持协议'));row.append(enableLabel);const options=el('div',undefined,'checks');const value=configured||{protocols:['chat'],preferredProtocol:'chat',nativeOnly:false};for(const [key,title] of Object.entries(protocolLabels)){const box=el('input');box.type='checkbox';box.checked=value.protocols.includes(key);box.disabled=!configured;box.addEventListener('change',()=>{if(box.checked)value.protocols.push(key);else value.protocols=value.protocols.filter(x=>x!==key);if(!value.protocols.includes(value.preferredProtocol))value.preferredProtocol=value.protocols[0]||'';modelProtocolDraft[model]=value;renderProtocols()});const label=el('label');label.append(box,document.createTextNode(' '+title));options.append(label)}row.append(options);const select=el('select');select.disabled=!configured;for(const key of value.protocols){const opt=el('option',protocolLabels[key]);opt.value=key;select.append(opt)}select.value=value.preferredProtocol;select.addEventListener('change',()=>{value.preferredProtocol=select.value;modelProtocolDraft[model]=value});const preferred=el('label','首选协议 ');preferred.append(select);row.append(preferred);const native=el('input');native.type='checkbox';native.checked=value.nativeOnly;native.disabled=!configured;native.addEventListener('change',()=>{value.nativeOnly=native.checked;modelProtocolDraft[model]=value});const nativeLabel=el('label');nativeLabel.append(native,document.createTextNode(' 强制原生，不切换接口'));row.append(nativeLabel);enabled.addEventListener('change',()=>{if(enabled.checked)modelProtocolDraft[model]=value;else delete modelProtocolDraft[model];renderProtocols()});root.append(row)}}
        function readProtocols(){const result={};for(const model of modelIds()){const value=modelProtocolDraft[model];if(!value)continue;if(!value.protocols.length||!value.protocols.includes(value.preferredProtocol))throw Error(model+' 必须选择支持协议及首选协议');result[model]=value}return result}
        $('syncProtocols').addEventListener('click',renderProtocols);
        load();})();
        </script></body></html>
        """);
}
